import {CountryWithTLD} from "../DTOs/LocationDTO/CountryWithTLD";
export const countries : CountryWithTLD[] = [
    { name: 'Afghanistan', tld: '.af' },
    { name: 'Albania', tld: '.al' },
    { name: 'Algeria', tld: '.dz' },
    { name: 'Andorra', tld: '.ad' },
    { name: 'Angola', tld: '.ao' },
    { name: 'Antigua and Barbuda', tld: '.ag' },
    { name: 'Argentina', tld: '.ar' },
    { name: 'Armenia', tld: '.am' },
    { name: 'Australia', tld: '.au' },
    { name: 'Austria', tld: '.at' },
    { name: 'Azerbaijan', tld: '.az' },
    { name: 'Bahamas', tld: '.bs' },
    { name: 'Bahrain', tld: '.bh' },
    { name: 'Bangladesh', tld: '.bd' },
    { name: 'Barbados', tld: '.bb' },
    { name: 'Belarus', tld: '.by' },
    { name: 'Belgium', tld: '.be' },
    { name: 'Belize', tld: '.bz' },
    { name: 'Benin', tld: '.bj' },
    { name: 'Bhutan', tld: '.bt' },
    { name: 'Bolivia', tld: '.bo' },
    { name: 'Bosnia and Herzegovina', tld: '.ba' },
    { name: 'Botswana', tld: '.bw' },
    { name: 'Brazil', tld: '.br' },
    { name: 'Brunei', tld: '.bn' },
    { name: 'Bulgaria', tld: '.bg' },
    { name: 'Burkina Faso', tld: '.bf' },
    { name: 'Burundi', tld: '.bi' },
    { name: 'Cabo Verde', tld: '.cv' },
    { name: 'Cambodia', tld: '.kh' },
    { name: 'Cameroon', tld: '.cm' },
    { name: 'Canada', tld: '.ca' },
    { name: 'Central African Republic', tld: '.cf' },
    { name: 'Chad', tld: '.td' },
    { name: 'Chile', tld: '.cl' },
    { name: 'China', tld: '.cn' },
    { name: 'Colombia', tld: '.co' },
    { name: 'Comoros', tld: '.km' },
    { name: 'Congo (Congo-Brazzaville)', tld: '.cg' },
    { name: 'Costa Rica', tld: '.cr' },
    { name: 'Croatia', tld: '.hr' },
    { name: 'Cuba', tld: '.cu' },
    { name: 'Cyprus', tld: '.cy' },
    { name: 'Czechia (Czech Republic)', tld: '.cz' },
    { name: 'Denmark', tld: '.dk' },
    { name: 'Djibouti', tld: '.dj' },
    { name: 'Dominica', tld: '.dm' },
    { name: 'Dominican Republic', tld: '.do' },
    { name: 'Ecuador', tld: '.ec' },
    { name: 'Egypt', tld: '.eg' },
    { name: 'El Salvador', tld: '.sv' },
    { name: 'Equatorial Guinea', tld: '.gq' },
    { name: 'Eritrea', tld: '.er' },
    { name: 'Estonia', tld: '.ee' },
    { name: 'Eswatini (fmr. "Swaziland")', tld: '.sz' },
    { name: 'Ethiopia', tld: '.et' },
    { name: 'Fiji', tld: '.fj' },
    { name: 'Finland', tld: '.fi' },
    { name: 'France', tld: '.fr' },
    { name: 'Gabon', tld: '.ga' },
    { name: 'Gambia', tld: '.gm' },
    { name: 'Georgia', tld: '.ge' },
    { name: 'Germany', tld: '.de' },
    { name: 'Ghana', tld: '.gh' },
    { name: 'Greece', tld: '.gr' },
    { name: 'Grenada', tld: '.gd' },
    { name: 'Guatemala', tld: '.gt' },
    { name: 'Guinea', tld: '.gn' },
    { name: 'Guinea-Bissau', tld: '.gw' },
    { name: 'Guyana', tld: '.gy' },
    { name: 'Haiti', tld: '.ht' },
    { name: 'Holy See', tld: '.va' },
    { name: 'Honduras', tld: '.hn' },
    { name: 'Hungary', tld: '.hu' },
    { name: 'Iceland', tld: '.is' },
    { name: 'India', tld: '.in' },
    { name: 'Indonesia', tld: '.id' },
    { name: 'Iran', tld: '.ir' },
    { name: 'Iraq', tld: '.iq' },
    { name: 'Ireland', tld: '.ie' },
    { name: 'Israel', tld: '.il' },
    { name: 'Italy', tld: '.it' },
    { name: 'Jamaica', tld: '.jm' },
    { name: 'Japan', tld: '.jp' },
    { name: 'Jordan', tld: '.jo' },
    { name: 'Kazakhstan', tld: '.kz' },
    { name: 'Kenya', tld: '.ke' },
    { name: 'Kiribati', tld: '.ki' },
    { name: 'Kuwait', tld: '.kw' },
    { name: 'Kyrgyzstan', tld: '.kg' },
    { name: 'Laos', tld: '.la' },
    { name: 'Latvia', tld: '.lv' },
    { name: 'Lebanon', tld: '.lb' },
    { name: 'Lesotho', tld: '.ls' },
    { name: 'Liberia', tld: '.lr' },
    { name: 'Libya', tld: '.ly' },
    { name: 'Liechtenstein', tld: '.li' },
    { name: 'Lithuania', tld: '.lt' },
    { name: 'Luxembourg', tld: '.lu' },
    { name: 'Madagascar', tld: '.mg' },
    { name: 'Malawi', tld: '.mw' },
    { name: 'Malaysia', tld: '.my' },
    { name: 'Maldives', tld: '.mv' },
    { name: 'Mali', tld: '.ml' },
    { name: 'Malta', tld: '.mt' },
    { name: 'Marshall Islands', tld: '.mh' },
    { name: 'Mauritania', tld: '.mr' },
    { name: 'Mauritius', tld: '.mu' },
    { name: 'Mexico', tld: '.mx' },
    { name: 'Micronesia', tld: '.fm' },
    { name: 'Moldova', tld: '.md' },
    { name: 'Monaco', tld: '.mc' },
    { name: 'Mongolia', tld: '.mn' },
    { name: 'Montenegro', tld: '.me' },
    { name: 'Morocco', tld: '.ma' },
    { name: 'Mozambique', tld: '.mz' },
    { name: 'Myanmar (formerly Burma)', tld: '.mm' },
    { name: 'Namibia', tld: '.na' },
    { name: 'Nauru', tld: '.nr' },
    { name: 'Nepal', tld: '.np' },
    { name: 'Netherlands', tld: '.nl' },
    { name: 'New Zealand', tld: '.nz' },
    { name: 'Nicaragua', tld: '.ni' },
    { name: 'Niger', tld: '.ne' },
    { name: 'Nigeria', tld: '.ng' },
    { name: 'North Korea', tld: '.kp' },
    { name: 'North Macedonia', tld: '.mk' },
    { name: 'Norway', tld: '.no' },
    { name: 'Oman', tld: '.om' },
    { name: 'Pakistan', tld: '.pk' },
    { name: 'Palau', tld: '.pw' },
    { name: 'Palestine State', tld: '.ps' },
    { name: 'Panama', tld: '.pa' },
    { name: 'Papua New Guinea', tld: '.pg' },
    { name: 'Paraguay', tld: '.py' },
    { name: 'Peru', tld: '.pe' },
    { name: 'Philippines', tld: '.ph' },
    { name: 'Poland', tld: '.pl' },
    { name: 'Portugal', tld: '.pt' },
    { name: 'Qatar', tld: '.qa' },
    { name: 'Romania', tld: '.ro' },
    { name: 'Russia', tld: '.ru' },
    { name: 'Rwanda', tld: '.rw' },
    { name: 'Saint Kitts and Nevis', tld: '.kn' },
    { name: 'Saint Lucia', tld: '.lc' },
    { name: 'Saint Vincent and the Grenadines', tld: '.vc' },
    { name: 'Samoa', tld: '.ws' },
    { name: 'San Marino', tld: '.sm' },
    { name: 'Sao Tome and Principe', tld: '.st' },
    { name: 'Saudi Arabia', tld: '.sa' },
    { name: 'Senegal', tld: '.sn' },
    { name: 'Serbia', tld: '.rs' },
    { name: 'Seychelles', tld: '.sc' },
    { name: 'Sierra Leone', tld: '.sl' },
    { name: 'Singapore', tld: '.sg' },
    { name: 'Slovakia', tld: '.sk' },
    { name: 'Slovenia', tld: '.si' },
    { name: 'Solomon Islands', tld: '.sb' },
    { name: 'Somalia', tld: '.so' },
    { name: 'South Africa', tld: '.za' },
    { name: 'South Korea', tld: '.kr' },
    { name: 'South Sudan', tld: '.ss' },
    { name: 'Spain', tld: '.es' },
    { name: 'Sri Lanka', tld: '.lk' },
    { name: 'Sudan', tld: '.sd' },
    { name: 'Suriname', tld: '.sr' },
    { name: 'Sweden', tld: '.se' },
    { name: 'Switzerland', tld: '.ch' },
    { name: 'Syria', tld: '.sy' },
    { name: 'Tajikistan', tld: '.tj' },
    { name: 'Tanzania', tld: '.tz' },
    { name: 'Thailand', tld: '.th' },
    { name: 'Timor-Leste', tld: '.tl' },
    { name: 'Togo', tld: '.tg' },
    { name: 'Tonga', tld: '.to' },
    { name: 'Trinidad and Tobago', tld: '.tt' },
    { name: 'Tunisia', tld: '.tn' },
    { name: 'Turkey', tld: '.tr' },
    { name: 'Turkmenistan', tld: '.tm' },
    { name: 'Tuvalu', tld: '.tv' },
    { name: 'Uganda', tld: '.ug' },
    { name: 'Ukraine', tld: '.ua' },
    { name: 'United Arab Emirates', tld: '.ae' },
    { name: 'United Kingdom', tld: '.uk' },
    { name: 'United States of America', tld: '.us' },
    { name: 'Uruguay', tld: '.uy' },
    { name: 'Uzbekistan', tld: '.uz' },
    { name: 'Vanuatu', tld: '.vu' },
    { name: 'Venezuela', tld: '.ve' },
    { name: 'Vietnam', tld: '.vn' },
    { name: 'Yemen', tld: '.ye' },
    { name: 'Zambia', tld: '.zm' },
    { name: 'Zimbabwe', tld: '.zw' },
];