import EmployeeBenefits from "../enums/modelDataEnums/EmployeeBenefits";
import {BenefitsStringMap} from "../DTOs/enumStringMapProfiles/BenefitsStringMap";


export const EmployeeBenefitsMapData: BenefitsStringMap[] = [
    {enumValue: EmployeeBenefits.DentalCare, stringValue: 'Dental care'},
    {enumValue: EmployeeBenefits.ExtendedHealthCare, stringValue: 'Extended health care'},
    {enumValue: EmployeeBenefits.LifeInsurance, stringValue: 'Life insurance'},
    {enumValue: EmployeeBenefits.RRSPMatch, stringValue: 'RRSP match'},
    {enumValue: EmployeeBenefits.PaidTimeOff, stringValue: 'Paid time off'},
    {enumValue: EmployeeBenefits.OnSiteParking, stringValue: 'On-site parking'},
    {enumValue: EmployeeBenefits.EmployeeAssistanceProgram, stringValue: 'Employee assistance program'},
    {enumValue: EmployeeBenefits.VisionCare, stringValue: 'Vision care'},
    {enumValue: EmployeeBenefits.DisabilityInsurance, stringValue: 'Disability insurance'},
    {enumValue: EmployeeBenefits.CasualDress, stringValue: 'Casual dress'},
    {enumValue: EmployeeBenefits.CompanyEvents, stringValue: 'Company events'},
    {enumValue: EmployeeBenefits.StoreDiscount, stringValue: 'Store discount'},
    {enumValue: EmployeeBenefits.CompanyPension, stringValue: 'Company pension'},
    {enumValue: EmployeeBenefits.TuitionReimbursement, stringValue: 'Tuition reimbursement'},
    {enumValue: EmployeeBenefits.WellnessProgram, stringValue: 'Wellness program'},
    {enumValue: EmployeeBenefits.DiscountedOrFreeFood, stringValue: 'Discounted or free food'},
    {enumValue: EmployeeBenefits.WorkFromHome, stringValue: 'Work from home'},
    {enumValue: EmployeeBenefits.ProfitSharing, stringValue: 'Profit sharing'},
    {enumValue: EmployeeBenefits.OnSiteGym, stringValue: 'On-site gym'},
    {enumValue: EmployeeBenefits.EmployeeStockPurchasePlan, stringValue: 'Employee stock purchase plan'},
    {enumValue: EmployeeBenefits.RelocationAssistance, stringValue: 'Relocation assistance'},
    {enumValue: EmployeeBenefits.CompanyCar, stringValue: 'Company car'},
    {enumValue: EmployeeBenefits.StockOptions, stringValue: 'Stock options'},
    {enumValue: EmployeeBenefits.CommuterBenefits, stringValue: 'Commuter benefits'},
    {enumValue: EmployeeBenefits.HousingAllowance, stringValue: 'Housing allowance'},
    {enumValue: EmployeeBenefits.AutomobileAllowance, stringValue: 'Automobile allowance'},
    {enumValue: EmployeeBenefits.LanguageTrainingProvided, stringValue: 'Language training provided'},
    {enumValue: EmployeeBenefits.OnSiteChildcare, stringValue: 'On-site childcare'},
    {enumValue: EmployeeBenefits.VRSP, stringValue: 'VRSP'},
    {enumValue: EmployeeBenefits.FlexibleSchedule, stringValue: 'Flexible schedule'},
    {enumValue: EmployeeBenefits.Other, stringValue: 'Other'},
];