// <auto-generated />
using ApplicationDAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationDAL.SearchContextMigrations
{
    [DbContext(typeof(SearchEngineContext))]
    partial class SearchEngineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApplicationDomain.IndexedModels.IndexedJobWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("IndexedJobWords");
                });

            modelBuilder.Entity("ApplicationDomain.IndexedModels.IndexedResumeWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("IndexedResumeWords");
                });

            modelBuilder.Entity("ApplicationDomain.IndexedModels.ProcessedJobWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IndexedJobWordId")
                        .HasColumnType("int");

                    b.Property<int>("JobWordOccurrences")
                        .HasColumnType("int");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndexedJobWordId");

                    b.ToTable("ProcessedJobsWords");
                });

            modelBuilder.Entity("ApplicationDomain.IndexedModels.ProcessedResumeWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IndexedResumeWordId")
                        .HasColumnType("int");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndexedResumeWordId");

                    b.ToTable("ProcessedResumesWords");
                });

            modelBuilder.Entity("ApplicationDomain.IndexedModels.ProcessedJobWord", b =>
                {
                    b.HasOne("ApplicationDomain.IndexedModels.IndexedJobWord", "IndexedJobWord")
                        .WithMany("ProcessedJobWords")
                        .HasForeignKey("IndexedJobWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndexedJobWord");
                });

            modelBuilder.Entity("ApplicationDomain.IndexedModels.ProcessedResumeWord", b =>
                {
                    b.HasOne("ApplicationDomain.IndexedModels.IndexedResumeWord", "IndexedResumeWord")
                        .WithMany("ProcessedResumeWords")
                        .HasForeignKey("IndexedResumeWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndexedResumeWord");
                });

            modelBuilder.Entity("ApplicationDomain.IndexedModels.IndexedJobWord", b =>
                {
                    b.Navigation("ProcessedJobWords");
                });

            modelBuilder.Entity("ApplicationDomain.IndexedModels.IndexedResumeWord", b =>
                {
                    b.Navigation("ProcessedResumeWords");
                });
#pragma warning restore 612, 618
        }
    }
}
